### ISSUE TITLE
Sequence alignment fails in many cases

### ISSUE THREAD

**Issue by violentinternet** [netzob/netzob#13] opened 2015-08-24 10:28 UTC
In many cases the alignment fails. The following exception is thrown when getCells() is called on a symbol after alignment:
`[...]File "/usr/lib/python2.7/site-packages/Netzob-1.0_git-py2.7-linux-x86_64.egg/netzob/Common/Utils/DataAlignment/ParallelDataAlignment.py", line 187, in execute
    raise Exception("At least one data ({0}) has not been successfully computed by the alignment".format(repr(d)))
Exception: At least one data ('\x01\x01\x06\x00j\x98/\x03\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00[...]`

To reproduce the issue you can use the following network trace:
https://violentinter.net/static/tmp/net-2009-11-13-09:24_dhcp2_trimmed.pcap
It's an publicly available trace originally from http://digitalcorpora.org/corp/nps/scenarios/2009-m57-patents/net/net-2009-11-13-09:24.pcap.gz 
The first linked pcap was filtered for dhcp traffic and then trimmed to 100 packets. 
To trigger the exception the following code can be used:
> from netzob.all import *
> messages = PCAPImporter.readFile('net-2009-11-13-09:24_dhcp2_trimmed.pcap').values()
> symbol = Symbol(messages=messages)
> Format.splitAligned(symbol, doInternalSlick=True)
> print symbol.getCells() # here the explosion happens

The exception of course is triggered using clusterByAlignment() too since splitAlignment() is called after clustering. 
I can reproduce this issue with a lot of different public traces. A few of them work well, most fail. 

Possible to influence: 
I noticed that that using "doInternalSlick=True" prevent the issue occurring for some traces. Also varying the equivalence sometimes help. 

Thanks in advance

**Comment by violentinternet** [comment] 2015-08-24 13:34
It could have something to do with symbol sizes. I just found out that all my network traces can be infered when I run clusterByAlignment() with minEquivalence of 80 or 90. So the symbols become very small (usually one or two message per symbol). Using splitAlignment() all messages are in one symbol, so that's even easier to trigger. 
Hope that helps.

**Comment by violentinternet** [comment] 2015-08-24 21:25
This issue can also be reproduced with v0.4.1. There's no error message on stdout and the GUI just hangs.

**Comment by gbossert** [comment] 2015-08-26 21:49
I can reproduce this issue with the following snippet.

```python
from netzob.all import *

message1 = '\x01\x01\x06\x00\x82=\x16\xc1\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00#\x8b4\xd4\xc4\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00c\x82Sc5\x01\x01t\x01\x01=\x07\x01\x00#\x8b4\xd4\xc4\x0c\x05Flame<\x08MSFT 5.07\x0b\x01\x0f\x03\x06,./\x1f!\xf9++\x02\xdc\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

message2 = '\x02\x01\x06\x00\x82=\x16\xc1\x00\x00\x00\x00\x00\x00\x00\x00\xc0\xa8\x01\x03\xc0\xa8\x01\x01\x00\x00\x00\x00\x00#\x8b4\xd4\xc4\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00domex.nps.edu\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00c\x82Sc5\x01\x026\x04\xc0\xa8\x01\x013\x04\x00\x00\r\xec\x01\x04\xff\xff\xff\x00\x0f\x00\x03\x04\xc0\xa8\x01\x01\x06\x04\xc0\xa8\x01\x01\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

messages = [RawMessage(message1), RawMessage(message2)]
symbol = Symbol(messages=messages)
Format.splitAligned(symbol, doInternalSlick=True)
print symbol.getCells() # here the explosion happens
```

**Comment by gbossert** [comment] 2015-08-27 06:28
The sequence alignment algorithm produces the following symbol structure:

```python
Symbol
|--  Field
     |--   Data (Raw=None ((0, 24)))
|--  Field
     |--   Data (Raw='\x06\x00\x82=\x16\xc1' ((0, 48)))
|--  Field
     |--   Data (Raw=None ((0, 8)))
|--  Field
     |--   Data (Raw='\x00\x00\x00\x00\x00\x00\x00\x00' ((0, 64)))
|--  Field
     |--   Data (Raw=None ((0, 64)))
|--  Field
     |--   Data (Raw='\x00\x00\x00\x00\x00' ((0, 40)))
|--  Field
     |--   Data (Raw=None ((0, 56)))
|--  Field
     |--   Data (Raw='#\x8b4\xd4\xc4\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' ((0, 120)))
|--  Field
     |--   Data (Raw=None ((0, 104)))
|--  Field
     |--   Data (Raw='\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' ((0, 1432)))
|--  Field
     |--   Data (Raw=None ((0, 120)))
|--  Field
     |--   Data (Raw='\x00\x00' ((0, 16)))
|--  Field
     |--   Data (Raw=None ((0, 184)))
|--  Field
     |--   Data (Raw='\x00\x00\x00\x00\x00\x00\x00\x00\x00' ((0, 72)))
|--  Field
     |--   Data (Raw=None ((0, 432)))
|--  Field
     |--   Data (Raw='\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' ((0, 80)))
|--  Field
     |--   Data (Raw=None ((0, 24)))
```

This structure embeds large fields (that accept many different values).
I bet the issue is related to the computational complexity (to be checked).
If so, to fix this, the sequence alignment must generate more precise fields structure.

**Comment by gbossert** [comment] 2015-08-27 12:06
The following field structure can be used to parse the two extracted messages.

```python
f1 = Field(Alt([Raw(nbBytes=0), Raw(nbBytes=2)])) # (0, 3)
f2 = Field(Raw('\x06\x00\x82=\x16\xc1')) 
f3 = Field(Alt([Raw(nbBytes=0), Raw(nbBytes=1)])) # (0, 1)
f4 = Field(Raw('\x00\x00\x00\x00\x00\x00\x00\x00'))
f5 = Field(Alt([Raw(nbBytes=0), Raw(nbBytes=8)])) # (0, 8)
f6 = Field(Raw('\x00\x00\x00\x00\x00'))
f7 = Field(Alt([Raw(nbBytes=0), Raw(nbBytes=7)])) # (0, 7)
f8 = Field(Raw('#\x8b4\xd4\xc4\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'))
f9 = Field(Alt([Raw(nbBytes=0), Raw(nbBytes=13)])) # (0, 13)
f10 = Field(Raw('\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'))
f11 = Field(Alt([Raw(nbBytes=0), Raw(nbBytes=15)])) # (0, 15)
f12 = Field(Raw('\x00\x00'))
f13 = Field(Alt([Raw(nbBytes=0), Raw(nbBytes=23)])) # (0, 23)
f14 = Field(Raw('\x00\x00\x00\x00\x00\x00\x00\x00\x00'))
f15 = Field(Alt([Raw(nbBytes=0), Raw(nbBytes=56)])) # (0, 54)
f16 = Field(Raw('\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'))
f17 = Field(Alt([Raw(nbBytes=0), Raw(nbBytes=5)])) # (0, 3)
```

Next to each dynamic field, I appended the original size value of the field as computed by the sequence alignment algorithm. It perhaps shows that the algorithm makes mistakes in the computation of fields length.

**Comment by gbossert** [comment] 2015-09-21 20:55
No mistakes were made by the Format inference algorithm. 
Instead, the produced symbol model was too complex to parse. Its parsing triggered a protection mechanism which silently killed parsing paths (it only kept the first 100 identified).

Based on this observation, three different fixes are necessary:
* the staticAligned method must generate simpler field definition
* the parser must be able to deal with more complex field definition
* the parser must log when the complexity threshold is reached.

I added some warning messages to address the third bug.
A more effective failback approach is also now used by the security mechanism. Not only the first 100 paths are retained but also the last 100.

**Comment by gbossert** [comment] 2015-09-24 17:26
I've updated the Netzob parser to support a more effective back-tracking mechanism as part of the second fix.
I believe this modification is a major one.
Based on your pcap, Netzob can easily display the computed alignment of the 20 first messages. When more messages are considered, the computed alignment is far too complex.

```
pcapFile = "dhcp2.pcap"
messages = PCAPImporter.readFile(pcapFile).values()[:20]
symbol = Symbol(messages=messages)
Format.splitAligned(symbol, doInternalSlick=True)
print symbol
```

I expect Netzob will be able to cope with the automatic alignment of your Pcap once the first fix is implemented.
In the meantime, can you have a look and tell me if you see something wrong such as regressions.

**Comment by skleber** [comment] 2015-11-23 21:17
After some testing with pcaps of at least 100 packets I am fairly sure the problem is resolved by the fix. The alignment never failed in any of my test cases. Thank you!

We have augmented our test-run wrapper-script with a mechanism to terminate the alignment (forcefully) if hitting a predefined timeout. This way the increased run times can be handled in a controlled way.

**Closed** 2015-12-07 17:54 UTC
